In [1]:
import numpy as np

In [2]:
Omega = np.array([[1, 0, 1],
                  [0,0,0], 
                  [1,0,1]])
Lambda = np.array([[2,1,1], 
                   [1,0,-1],
                   [1,-1, 2]])

In [3]:
Omega

array([[1, 0, 1],
       [0, 0, 0],
       [1, 0, 1]])

In [4]:
Lambda

array([[ 2,  1,  1],
       [ 1,  0, -1],
       [ 1, -1,  2]])

In [5]:
U = np.array([[-1/np.sqrt(6), -1/np.sqrt(3), 1/np.sqrt(2)], 
              [2/np.sqrt(6), -1/np.sqrt(3), 0],
              [1/np.sqrt(6), 1/np.sqrt(3), 1/np.sqrt(2)]])

In [6]:
U

array([[-0.40824829, -0.57735027,  0.70710678],
       [ 0.81649658, -0.57735027,  0.        ],
       [ 0.40824829,  0.57735027,  0.70710678]])

In [7]:
U.T

array([[-0.40824829,  0.81649658,  0.40824829],
       [-0.57735027, -0.57735027,  0.57735027],
       [ 0.70710678,  0.        ,  0.70710678]])

In [18]:
np.matmul(np.matmul(U.T, Omega), U)

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -4.90285357e-17,   3.55923857e-17,   2.00000000e+00]])

In [19]:
np.matmul(np.matmul(U.T, Lambda), U)

array([[ -1.00000000e+00,   2.09522145e-17,   6.37665793e-17],
       [  1.33216630e-16,   2.00000000e+00,  -1.86452219e-16],
       [ -1.80316523e-17,  -5.76337239e-17,   3.00000000e+00]])